// app/layout.tsx
import { Inter, Poppins, Epilogue } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./redux/ReduxProvider"; // Import the Redux provider

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className="font-Epilogue">
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
