// app/layout.tsx
import { Inter, Poppins, Epilogue } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./redux/ReduxProvider"; // Import the Redux provider
import SessionWrapper from "./components/sessionWraper";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en" className="h-screen">
        <head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
        </head>
        <body className="font-Epilogue flex items-center justify-center py-8">
          <ReduxProvider>{children}</ReduxProvider>
        </body>
      </html>
    </SessionWrapper>
  );
}
